name: Update knowledge.json

on:
  schedule:
    - cron: '0 18 * * *'  # 毎日03:00 JST（UTC 18:00）
  workflow_dispatch:

concurrency:
  group: update-knowledge
  cancel-in-progress: true

jobs:
  update-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gspread oauth2client numpy openai faiss-cpu python-dotenv

      - name: Write credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Generate knowledge.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/generate_knowledge.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/knowledge.json
          git commit -m "Auto update knowledge.json" || echo "No changes to commit"
          git push
